# Load required packages
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(stringr)
library(plotly)
library(DT)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(GenomicRanges)
library(org.Hs.eg.db)
library(RITANdata)
library(RITAN)
library(Biostrings)
library(BSgenome.Hsapiens.UCSC.hg19)
